name: FlashThread
description: "FlashThread Application for Messaging"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  simple_gradient_text: 1.3.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  flutter_native_splash: ^2.3.10
  simple_animations: ^5.0.2
  flutter_launcher_icons: ^0.13.1
  gradient_icon: ^2.0.9
  rename_app: ^1.3.2
  page_transition: ^2.1.0
  confirm_dialog: ^1.0.3
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

  assets:
    - assets/images/side-icons/flash-thread.png
    - assets/images/side-icons/flash-thread-colors.png
    - assets/images/side-icons/flash-thread-withe.png
    - assets/images/splash/splash_dark.png
    - assets/images/load/load.jpg
    - assets/images/load/loading.gif
    - assets/images/icon.png
    - assets/audios/tones.mp3
    - assets/audios/send-tone.mp3


flutter_native_splash:
  image: assets/images/splash/splash_dark.png
  color: '#000000'
  android_12:
    image: assets/images/splash/splash_dark.png
    icon_background_color: "#000000"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/images/icon.png
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: assets/images/icon.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/images/icon.png